<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#question-2" data-toc-modified-id="question-2-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>question 2</a></span></li></ul></div>

In [1]:
import numpy as np

In [2]:
dataraw = """\
...........
.....###.#.
.###.##..#.
..#.#...#..
....#.#....
.##..S####.
.##..#...#.
.......##..
.##.#.####.
.##..##.##.
...........
"""

In [19]:
with open("input.txt") as f:
    dataraw = f.read()
dataraw[-5:]

'....\n'

In [20]:
dataraw = dataraw.replace(".","0").replace("#",'1').replace('S',"2").split("\n")
stones = np.array([ list(dat) for dat in dataraw[:-1] ], dtype=int)
print(stones, stones.shape)
xstarts, ystarts = np.where(stones==2)
stones[(xstarts, ystarts)]=0
xstarts, ystarts

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 0 1 0]
 [0 0 0 ... 0 0 0]] (131, 131)


(array([65]), array([65]))

In [21]:
lim = stones.shape[0]
lim

131

In [26]:
def get_new_indices(R, lim):
    X, Y = [], []
    for i in range(len(R)):
        xstart, ystart = R[i]
        X.extend([xstart, xstart, xstart-1, xstart+1])
        Y.extend([ystart-1, ystart+1, ystart, ystart])
    R = np.c_[X, Y]
    mask = np.any((R > lim)|(R<0), axis=1)
    R = R[~mask]
    R = R[stones[tuple(R.T)]==0]
    R = np.unique(R, axis=0)
    return R

In [27]:
R = np.array(np.c_[xstarts, ystarts])
for _ in range(64):
    R = get_new_indices(R, lim)
len(R)

3770

## question 2

In [8]:
(26501365 - 65) / 131

202300.0

In [38]:
tiled_stones = np.tile(stones, (5, 5))
tiled_stones.shape

(655, 655)

In [42]:
def get_new_indices(R):
    X, Y = [], []
    for i in range(len(R)):
        xstart, ystart = R[i]
        X.extend([xstart, xstart, xstart-1, xstart+1])
        Y.extend([ystart-1, ystart+1, ystart, ystart])
    R = np.c_[X, Y]
    #R%=131
    #mask = np.any((R > lim)|(R<0), axis=1)
    #R = R[~mask]
    R = R[tiled_stones[tuple(R.T)]==0]
    R = np.unique(R, axis=0)
    return R

In [45]:
X = [65, 65+131, 65+131*2]
R = np.array(np.c_[xstarts+2*131, ystarts+2*131])
Y = []
for i in range(65+131*2):
    R = get_new_indices(R)
    if i+1 in X:
        print(i, len(R))
        Y.append(len(R))
X, Y

64 3885
195 34700
326 96215


([65, 196, 327], [3885, 34700, 96215])

In [46]:
coefficients = np.polyfit([0,1,2], Y, deg=2) 
coefficients

array([15350., 15465.,  3885.])

In [49]:
y_final = np.polyval(coefficients, 202300) # using coefficients, get y value at x_final
y_final.round().astype(int)

628206330073385