In [1]:
import numpy as np

In [ ]:
dataraw = """\
...........
.....###.#.
.###.##..#.
..#.#...#..
....#.#....
.##..S####.
.##..#...#.
.......##..
.##.#.####.
.##..##.##.
..........."""

In [121]:
with open("input.txt") as f:
    dataraw = f.read()
dataraw[-5:]

'....\n'

In [122]:
dataraw = dataraw.replace(".","0").replace("#",'1').replace('S',"2").split("\n")
stones = np.array([ list(dat) for dat in dataraw[:-1] ], dtype=int)
print(stones, stones.shape)
xstarts, ystarts = np.where(stones==2)
xstarts, ystarts

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 0 1 0]
 [0 0 0 ... 0 0 0]] (131, 131)


(array([65]), array([65]))

In [142]:
lim = stones.shape[0]
lim

131

In [148]:
def get_new_indices(R, lim):
    X, Y = [], []
    for i in range(len(R)):
        xstart, ystart = R[i]
        X.extend([xstart, xstart, xstart-1, xstart+1])
        Y.extend([ystart-1, ystart+1, ystart, ystart])
    R = np.c_[X, Y]
    mask = np.any((R > lim)|(R<0), axis=1)
    R = R[~mask]
    R = R[stones[tuple(R.T)]==0]
    R = np.unique(R, axis=0)
    return R

In [152]:
R = np.array(np.c_[xstarts, ystarts])
for _ in range(64):
    R = get_new_indices(R, lim)
len(R)+1

3770

## question 2

In [105]:
positions = stones.copy()
positions[tuple(R.T)] = 3
positions

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0],
       [0, 1, 1, 1, 0, 1, 1, 0, 3, 1, 0],
       [0, 3, 1, 3, 1, 3, 0, 3, 1, 0, 0],
       [3, 0, 3, 0, 1, 0, 1, 0, 3, 0, 0],
       [0, 1, 1, 3, 0, 2, 1, 1, 1, 1, 0],
       [0, 1, 1, 0, 3, 1, 3, 0, 0, 1, 0],
       [0, 3, 0, 3, 0, 3, 0, 1, 1, 0, 0],
       [0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0],
       [0, 1, 1, 3, 0, 1, 1, 0, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [136]:
print(stones)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 0 1 0]
 [0 0 0 ... 0 0 0]]
